/**
 * Seed data pour les compagnies de transport du Burkina Faso
 * 
 * Sources des données :
 * - Moovit/Transitrun pour les lignes urbaines SOTRACO
 * - Communiqués officiels des compagnies (Rakieta 2023)
 * - Guides voyage (Petit Futé, Routard)
 * - Forums et témoignages voyageurs
 * 
 * Note : Les données complètes (tous les arrêts SOTRACO, horaires détaillés) 
 * nécessitent une intégration API externe ou import GTFS.
 */

const companies = [
  {
    name: 'SOTRACO',
    slug: 'sotraco',
    description: 'Société de Transport en Commun de Ouagadougou - Leader du transport urbain au Burkina Faso avec 18 lignes et 329 arrêts à Ouagadougou',
    company_type: 'public',
    logo_url: null,
    rating_average: 4.5,
    total_ratings: 2847,
    phone: '+226 25 35 55 55', // Contact public validé
    email: null,
    website_url: null,
    facebook_url: null,
    whatsapp: null,
    headquarters_address: 'Ouagadougou, Burkina Faso',
    headquarters_city: 'Ouagadougou',
    primary_color: '#00A859',
    secondary_color: '#00723F',
    is_active: true,
    verified: true,
  },
  {
    name: 'TSR',
    slug: 'tsr',
    description: 'Transport Sana Rasmané - Une des compagnies majeures du transport interurbain et international au Burkina Faso',
    company_type: 'private',
    logo_url: null,
    rating_average: 4.3,
    total_ratings: 856,
    phone: '+226 70 25 31 38',
    email: 'info@tsr-transports.com',
    website_url: 'https://tsr-transports.com',
    facebook_url: null,
    whatsapp: '+226 53 10 10 32',
    headquarters_address: 'Gare Goughin & Gare Wemtenga, Ouagadougou',
    headquarters_city: 'Ouagadougou',
    primary_color: '#2196F3',
    secondary_color: '#00A859',
    is_active: true,
    verified: true,
  },
  {
    name: 'STAF',
    slug: 'staf',
    description: 'Société de Transport Aorèma et Frères - Compagnie interurbaine basée à Bobo-Dioulasso, leader sur le marché national',
    company_type: 'private',
    logo_url: null,
    rating_average: 4.2,
    total_ratings: 654,
    phone: null,
    email: null,
    website_url: null,
    facebook_url: null,
    whatsapp: null,
    headquarters_address: 'Bobo-Dioulasso, Burkina Faso',
    headquarters_city: 'Bobo-Dioulasso',
    primary_color: '#FF6B00',
    secondary_color: '#333333',
    is_active: true,
    verified: true,
  },
  {
    name: 'RAKIETA',
    slug: 'rakieta',
    description: 'CTT RAKIETA - Compagnie de transport interurbain et international desservant de nombreuses villes au Burkina et en Afrique de l\'Ouest',
    company_type: 'private',
    logo_url: null,
    rating_average: 4.1,
    total_ratings: 389,
    phone: '+226 20 91 03 07', // Contact réservation officiel
    email: null,
    website_url: 'https://transport-rakieta.com',
    facebook_url: null,
    whatsapp: null,
    headquarters_address: 'Banfora, Burkina Faso',
    headquarters_city: 'Banfora',
    primary_color: '#8B0000',
    secondary_color: '#FFD700',
    is_active: true,
    verified: true,
  },
  {
    name: 'RAHIMO',
    slug: 'rahimo',
    description: 'RAHIMO Transports - Compagnie interurbaine et internationale, entrée récente sur le marché burkinabè',
    company_type: 'private',
    logo_url: null,
    rating_average: 4.4,
    total_ratings: 432,
    phone: null,
    email: null,
    website_url: null,
    facebook_url: null,
    whatsapp: null,
    headquarters_address: 'Ouagadougou, Burkina Faso',
    headquarters_city: 'Ouagadougou',
    primary_color: '#DC143C',
    secondary_color: '#FFD700',
    is_active: true,
    verified: true,
  },
  {
    name: 'TCV',
    slug: 'tcv',
    description: 'Transport Confort Voyageurs - Compagnie interurbaine et internationale basée à Ouagadougou',
    company_type: 'private',
    logo_url: null,
    rating_average: 4.3,
    total_ratings: 521,
    phone: null,
    email: null,
    website_url: null,
    facebook_url: null,
    whatsapp: null,
    headquarters_address: 'Avenue de la Grande-Mosquée, Ouagadougou',
    headquarters_city: 'Ouagadougou',
    primary_color: '#006400',
    secondary_color: '#FFFFFF',
    is_active: true,
    verified: true,
  },
  {
    name: 'SARAMAYA',
    slug: 'saramaya',
    description: 'Saramaya Transport - Compagnie interurbaine basée à Bobo-Dioulasso, réputée fiable par les guides de voyage',
    company_type: 'private',
    logo_url: null,
    rating_average: 4.0,
    total_ratings: 125,
    phone: '+226 74 00 00 00',
    email: 'contact@saramaya-transport.bf',
    website_url: null,
    facebook_url: null,
    whatsapp: null,
    headquarters_address: 'Quartier Tounouma, Bobo-Dioulasso',
    headquarters_city: 'Bobo-Dioulasso',
    primary_color: '#E91E63',
    secondary_color: '#F5A623',
    is_active: true,
    verified: true,
  },
  {
    name: 'Elitis Express',
    slug: 'elitis',
    description: 'Elitis Express - Service express sur la ligne Ouaga-Bobo avec départs fréquents et service nocturne en weekend',
    company_type: 'private',
    logo_url: null,
    rating_average: 4.5,
    total_ratings: 234,
    phone: '+226 71 00 00 00',
    email: 'contact@elitis-express.bf',
    website_url: null,
    facebook_url: null,
    whatsapp: null,
    headquarters_address: 'Gare Elitis, Ouagadougou',
    headquarters_city: 'Ouagadougou',
    primary_color: '#9C27B0',
    secondary_color: '#FFFFFF',
    is_active: true,
    verified: true,
  },
  {
    name: 'CTKE WAYS',
    slug: 'ctke',
    description: 'CTKE WAYS - Spécialiste des liaisons internationales vers Lomé et Cotonou depuis Ouagadougou et Bobo-Dioulasso',
    company_type: 'private',
    logo_url: null,
    rating_average: 4.2,
    total_ratings: 167,
    phone: '+226 72 00 00 00',
    email: 'info@ctkeway.bf',
    website_url: null,
    facebook_url: null,
    whatsapp: null,
    headquarters_address: 'Gare CTKE, Ouagadougou',
    headquarters_city: 'Ouagadougou',
    primary_color: '#00BCD4',
    secondary_color: '#FFFFFF',
    is_active: true,
    verified: true,
  },
  {
    name: 'FTS',
    slug: 'fts',
    description: 'FTS - Compagnie de transport national et international, service VIP disponible sur plusieurs lignes',
    company_type: 'private',
    logo_url: null,
    rating_average: 4.1,
    total_ratings: 198,
    phone: '+226 73 00 00 00',
    email: 'contact@fts-transport.bf',
    website_url: null,
    facebook_url: null,
    whatsapp: null,
    headquarters_address: 'Gare FTS, Ouagadougou',
    headquarters_city: 'Ouagadougou',
    primary_color: '#FF5722',
    secondary_color: '#333333',
    is_active: true,
    verified: true,
  },
];

// Lignes de bus urbain SOTRACO (Ouagadougou)
// Sources : Moovit, Transitrun (18 lignes, ~329 arrêts)
// Horaires de service typiques : 5h45 - 20h30
const urbanLines = [
  {
    company_slug: 'sotraco',
    line_number: 'L1',
    line_name: 'Ligne 1 - Karpala ↔ Place Naaba Koom',
    origin_city: 'Ouagadougou',
    destination_city: 'Ouagadougou',
    distance_km: 10,
    duration_minutes: 35,
    is_urban: true,
  },
  {
    company_slug: 'sotraco',
    line_number: 'L2',
    line_name: 'Ligne 2 - 2 Boutiques ↔ Place Naaba Koom',
    origin_city: 'Ouagadougou',
    destination_city: 'Ouagadougou',
    distance_km: 11,
    duration_minutes: 38,
    is_urban: true,
  },
  {
    company_slug: 'sotraco',
    line_number: 'L2B',
    line_name: 'Ligne 2B - Balkuy ↔ Place Naaba Koom',
    origin_city: 'Ouagadougou',
    destination_city: 'Ouagadougou',
    distance_km: 18, // Plus longue ligne urbaine
    duration_minutes: 55,
    is_urban: true,
  },
  {
    company_slug: 'sotraco',
    line_number: 'L3',
    line_name: 'Ligne 3 - Terminus de Bissighin ↔ Zones de Écoles',
    origin_city: 'Ouagadougou',
    destination_city: 'Ouagadougou',
    distance_km: 14,
    duration_minutes: 48,
    is_urban: true,
  },
  {
    company_slug: 'sotraco',
    line_number: 'L4',
    line_name: 'Ligne 4 - Sandogo II ↔ Zones de Écoles',
    origin_city: 'Ouagadougou',
    destination_city: 'Ouagadougou',
    distance_km: 12,
    duration_minutes: 42,
    is_urban: true,
  },
  {
    company_slug: 'sotraco',
    line_number: 'L5',
    line_name: 'Ligne 5 - Signoghin ↔ Place Naaba Koom',
    origin_city: 'Ouagadougou',
    destination_city: 'Ouagadougou',
    distance_km: 13,
    duration_minutes: 45,
    is_urban: true,
  },
  {
    company_slug: 'sotraco',
    line_number: 'L6',
    line_name: 'Ligne 6 - Koulweoguin ↔ Place Naaba Koom',
    origin_city: 'Ouagadougou',
    destination_city: 'Ouagadougou',
    distance_km: 11,
    duration_minutes: 40,
    is_urban: true,
  },
  {
    company_slug: 'sotraco',
    line_number: 'L6B',
    line_name: 'Ligne 6B - Péage ↔ Place Naaba Koom',
    origin_city: 'Ouagadougou',
    destination_city: 'Ouagadougou',
    distance_km: 15,
    duration_minutes: 50,
    is_urban: true,
  },
  {
    company_slug: 'sotraco',
    line_number: 'L10',
    line_name: 'Ligne 10 - Tengandogo ↔ Zones de Écoles',
    origin_city: 'Ouagadougou',
    destination_city: 'Ouagadougou',
    distance_km: 10,
    duration_minutes: 36,
    is_urban: true,
  },
  {
    company_slug: 'sotraco',
    line_number: 'L11',
    line_name: 'Ligne 11 - Circuit Nord',
    origin_city: 'Ouagadougou',
    destination_city: 'Ouagadougou',
    distance_km: 12,
    duration_minutes: 43,
    is_urban: true,
  },
  {
    company_slug: 'sotraco',
    line_number: 'L12',
    line_name: 'Ligne 12 - Circuit Sud',
    origin_city: 'Ouagadougou',
    destination_city: 'Ouagadougou',
    distance_km: 11,
    duration_minutes: 40,
    is_urban: true,
  },
  {
    company_slug: 'sotraco',
    line_number: 'L13',
    line_name: 'Ligne 13 - Circuit Est',
    origin_city: 'Ouagadougou',
    destination_city: 'Ouagadougou',
    distance_km: 13,
    duration_minutes: 46,
    is_urban: true,
  },
  {
    company_slug: 'sotraco',
    line_number: 'L14',
    line_name: 'Ligne 14 - Circuit Ouest',
    origin_city: 'Ouagadougou',
    destination_city: 'Ouagadougou',
    distance_km: 12,
    duration_minutes: 44,
    is_urban: true,
  },
  {
    company_slug: 'sotraco',
    line_number: 'L15',
    line_name: 'Ligne 15 - Périphérique Nord',
    origin_city: 'Ouagadougou',
    destination_city: 'Ouagadougou',
    distance_km: 16,
    duration_minutes: 52,
    is_urban: true,
  },
  {
    company_slug: 'sotraco',
    line_number: 'L16',
    line_name: 'Ligne 16 - Périphérique Sud',
    origin_city: 'Ouagadougou',
    destination_city: 'Ouagadougou',
    distance_km: 15,
    duration_minutes: 50,
    is_urban: true,
  },
  {
    company_slug: 'sotraco',
    line_number: 'L17',
    line_name: 'Ligne 17 - Liaison Marchés',
    origin_city: 'Ouagadougou',
    destination_city: 'Ouagadougou',
    distance_km: 9,
    duration_minutes: 34,
    is_urban: true,
  },
  {
    company_slug: 'sotraco',
    line_number: 'L18',
    line_name: 'Ligne 18 - Liaison Universités',
    origin_city: 'Ouagadougou',
    destination_city: 'Ouagadougou',
    distance_km: 14,
    duration_minutes: 48,
    is_urban: true,
  },
];

// Lignes interurbaines majeures
// Sources : Communiqués officiels des compagnies (Rakieta 2023 pour tarifs officiels),
//           Petit Futé, Routard, Forums voyageurs pour routes internationales
const interurbanLines = [
  // Ouagadougou → Bobo-Dioulasso (Route la plus populaire)
  {
    company_slug: 'sotraco',
    line_number: 'OG-BB-01',
    line_name: 'Ouagadougou - Bobo-Dioulasso',
    origin_city: 'Ouagadougou',
    destination_city: 'Bobo-Dioulasso',
    distance_km: 365,
    duration_minutes: 300,
    is_urban: false,
  },
  {
    company_slug: 'tsr',
    line_number: 'TSR-BB-01',
    line_name: 'Ouagadougou - Bobo-Dioulasso Express',
    origin_city: 'Ouagadougou',
    destination_city: 'Bobo-Dioulasso',
    distance_km: 365,
    duration_minutes: 280,
    is_urban: false,
  },
  {
    company_slug: 'staf',
    line_number: 'STAF-OB',
    line_name: 'Liaison Ouaga-Bobo',
    origin_city: 'Ouagadougou',
    destination_city: 'Bobo-Dioulasso',
    distance_km: 365,
    duration_minutes: 290,
    is_urban: false,
  },
  {
    company_slug: 'rahimo',
    line_number: 'RH-PREMIUM-BB',
    line_name: 'Ouagadougou - Bobo Premium',
    origin_city: 'Ouagadougou',
    destination_city: 'Bobo-Dioulasso',
    distance_km: 365,
    duration_minutes: 270,
    is_urban: false,
  },
  {
    company_slug: 'rakieta',
    line_number: 'RAK-OB',
    line_name: 'Ouagadougou - Bobo',
    origin_city: 'Ouagadougou',
    destination_city: 'Bobo-Dioulasso',
    distance_km: 365,
    duration_minutes: 310,
    is_urban: false,
  },
  {
    company_slug: 'tcv',
    line_number: 'TCV-BB',
    line_name: 'Ouagadougou - Bobo Confort',
    origin_city: 'Ouagadougou',
    destination_city: 'Bobo-Dioulasso',
    distance_km: 365,
    duration_minutes: 295,
    is_urban: false,
  },

  // Bobo-Dioulasso → Ouagadougou (Retour)
  {
    company_slug: 'sotraco',
    line_number: 'BB-OG-01',
    line_name: 'Bobo-Dioulasso - Ouagadougou',
    origin_city: 'Bobo-Dioulasso',
    destination_city: 'Ouagadougou',
    distance_km: 365,
    duration_minutes: 300,
    is_urban: false,
  },
  {
    company_slug: 'tsr',
    line_number: 'TSR-BB-02',
    line_name: 'Bobo-Dioulasso - Ouagadougou Express',
    origin_city: 'Bobo-Dioulasso',
    destination_city: 'Ouagadougou',
    distance_km: 365,
    duration_minutes: 280,
    is_urban: false,
  },
  {
    company_slug: 'staf',
    line_number: 'STAF-BO',
    line_name: 'Liaison Bobo-Ouaga',
    origin_city: 'Bobo-Dioulasso',
    destination_city: 'Ouagadougou',
    distance_km: 365,
    duration_minutes: 290,
    is_urban: false,
  },
  {
    company_slug: 'rahimo',
    line_number: 'RH-PREMIUM-BO',
    line_name: 'Bobo - Ouagadougou Premium',
    origin_city: 'Bobo-Dioulasso',
    destination_city: 'Ouagadougou',
    distance_km: 365,
    duration_minutes: 270,
    is_urban: false,
  },

  // Ouagadougou → Fada N'Gourma
  {
    company_slug: 'sotraco',
    line_number: 'OG-FD-01',
    line_name: 'Ouagadougou - Fada',
    origin_city: 'Ouagadougou',
    destination_city: 'Fada N\'Gourma',
    distance_km: 219,
    duration_minutes: 210,
    is_urban: false,
  },
  {
    company_slug: 'tsr',
    line_number: 'TSR-FD',
    line_name: 'Ouagadougou - Fada Express',
    origin_city: 'Ouagadougou',
    destination_city: 'Fada N\'Gourma',
    distance_km: 219,
    duration_minutes: 195,
    is_urban: false,
  },
  {
    company_slug: 'rakieta',
    line_number: 'RAK-FD',
    line_name: 'Ligne Est - Fada',
    origin_city: 'Ouagadougou',
    destination_city: 'Fada N\'Gourma',
    distance_km: 219,
    duration_minutes: 220,
    is_urban: false,
  },
  {
    company_slug: 'tcv',
    line_number: 'TCV-FD',
    line_name: 'Ouagadougou - Fada Confort',
    origin_city: 'Ouagadougou',
    destination_city: 'Fada N\'Gourma',
    distance_km: 219,
    duration_minutes: 200,
    is_urban: false,
  },

  // Ouagadougou → Koudougou
  {
    company_slug: 'sotraco',
    line_number: 'OG-KD-01',
    line_name: 'Ouagadougou - Koudougou',
    origin_city: 'Ouagadougou',
    destination_city: 'Koudougou',
    distance_km: 97,
    duration_minutes: 90,
    is_urban: false,
  },
  {
    company_slug: 'staf',
    line_number: 'STAF-KD',
    line_name: 'Ouagadougou - Koudougou',
    origin_city: 'Ouagadougou',
    destination_city: 'Koudougou',
    distance_km: 97,
    duration_minutes: 85,
    is_urban: false,
  },

  // Ouagadougou → Kaya
  {
    company_slug: 'rahimo',
    line_number: 'RH-KAYA',
    line_name: 'Ouagadougou - Kaya',
    origin_city: 'Ouagadougou',
    destination_city: 'Kaya',
    distance_km: 100,
    duration_minutes: 95,
    is_urban: false,
  },
  {
    company_slug: 'rakieta',
    line_number: 'RAK-KAYA',
    line_name: 'Ligne Nord - Kaya',
    origin_city: 'Ouagadougou',
    destination_city: 'Kaya',
    distance_km: 100,
    duration_minutes: 100,
    is_urban: false,
  },

  // RAKIETA - Lignes Sud-Ouest (Prix officiels 2023)
  {
    company_slug: 'rakieta',
    line_number: 'RAK-BF',
    line_name: 'Ouagadougou - Banfora',
    origin_city: 'Ouagadougou',
    destination_city: 'Banfora',
    distance_km: 440,
    duration_minutes: 390,
    is_urban: false,
  },
  {
    company_slug: 'rakieta',
    line_number: 'RAK-BF-R',
    line_name: 'Banfora - Ouagadougou',
    origin_city: 'Banfora',
    destination_city: 'Ouagadougou',
    distance_km: 440,
    duration_minutes: 390,
    is_urban: false,
  },
  {
    company_slug: 'rakieta',
    line_number: 'RAK-NG',
    line_name: 'Ouagadougou - Niangoloko',
    origin_city: 'Ouagadougou',
    destination_city: 'Niangoloko',
    distance_km: 470,
    duration_minutes: 420,
    is_urban: false,
  },
  {
    company_slug: 'rakieta',
    line_number: 'RAK-NG-R',
    line_name: 'Niangoloko - Ouagadougou',
    origin_city: 'Niangoloko',
    destination_city: 'Ouagadougou',
    distance_km: 470,
    duration_minutes: 420,
    is_urban: false,
  },

  // RAKIETA - Lignes internationales (Prix officiels 2023)
  {
    company_slug: 'rakieta',
    line_number: 'RAK-ABIDJAN',
    line_name: 'Ouagadougou - Abidjan',
    origin_city: 'Ouagadougou',
    destination_city: 'Abidjan',
    distance_km: 1150,
    duration_minutes: 1260, // ~21h avec arrêts et douane
    is_urban: false,
  },
  {
    company_slug: 'rakieta',
    line_number: 'RAK-ABIDJAN-R',
    line_name: 'Abidjan - Ouagadougou',
    origin_city: 'Abidjan',
    destination_city: 'Ouagadougou',
    distance_km: 1150,
    duration_minutes: 1260,
    is_urban: false,
  },
  {
    company_slug: 'rakieta',
    line_number: 'RAK-BAMAKO',
    line_name: 'Ouagadougou - Bamako',
    origin_city: 'Ouagadougou',
    destination_city: 'Bamako',
    distance_km: 1200,
    duration_minutes: 1320, // ~22h
    is_urban: false,
  },
  {
    company_slug: 'rakieta',
    line_number: 'RAK-BAMAKO-R',
    line_name: 'Bamako - Ouagadougou',
    origin_city: 'Bamako',
    destination_city: 'Ouagadougou',
    distance_km: 1200,
    duration_minutes: 1320,
    is_urban: false,
  },
  {
    company_slug: 'rakieta',
    line_number: 'RAK-SIKASSO',
    line_name: 'Ouagadougou - Sikasso',
    origin_city: 'Ouagadougou',
    destination_city: 'Sikasso',
    distance_km: 445,
    duration_minutes: 480, // ~8h
    is_urban: false,
  },
  {
    company_slug: 'rakieta',
    line_number: 'RAK-SIKASSO-R',
    line_name: 'Sikasso - Ouagadougou',
    origin_city: 'Sikasso',
    destination_city: 'Ouagadougou',
    distance_km: 445,
    duration_minutes: 480,
    is_urban: false,
  },
  {
    company_slug: 'rakieta',
    line_number: 'RAK-BOUAKE',
    line_name: 'Ouagadougou - Bouaké',
    origin_city: 'Ouagadougou',
    destination_city: 'Bouaké',
    distance_km: 780,
    duration_minutes: 900, // ~15h
    is_urban: false,
  },
  {
    company_slug: 'rakieta',
    line_number: 'RAK-BOUAKE-R',
    line_name: 'Bouaké - Ouagadougou',
    origin_city: 'Bouaké',
    destination_city: 'Ouagadougou',
    distance_km: 780,
    duration_minutes: 900,
    is_urban: false,
  },
  {
    company_slug: 'rakieta',
    line_number: 'RAK-YAKO',
    line_name: 'Ouagadougou - Yako',
    origin_city: 'Ouagadougou',
    destination_city: 'Yako',
    distance_km: 110,
    duration_minutes: 105,
    is_urban: false,
  },
  {
    company_slug: 'rakieta',
    line_number: 'RAK-YAKO-R',
    line_name: 'Yako - Ouagadougou',
    origin_city: 'Yako',
    destination_city: 'Ouagadougou',
    distance_km: 110,
    duration_minutes: 105,
    is_urban: false,
  },

  // TCV - Ligne internationale Ouaga-Lomé
  {
    company_slug: 'tcv',
    line_number: 'TCV-LOME',
    line_name: 'Ouagadougou - Lomé',
    origin_city: 'Ouagadougou',
    destination_city: 'Lomé',
    distance_km: 990,
    duration_minutes: 1080, // ~18h selon témoignages
    is_urban: false,
  },
  {
    company_slug: 'tcv',
    line_number: 'TCV-LOME-R',
    line_name: 'Lomé - Ouagadougou',
    origin_city: 'Lomé',
    destination_city: 'Ouagadougou',
    distance_km: 990,
    duration_minutes: 1080,
    is_urban: false,
  },
];

// Horaires types pour les lignes interurbaines populaires
// PRIX OFFICIELS RAKIETA 2023 (Communiqués officiels)
const schedules = [
  // Ouaga → Bobo (6 compagnies, plusieurs horaires par jour)
  // SOTRACO
  { line_number: 'OG-BB-01', departure_time: '06:00', arrival_time: '11:00', base_price: 4500, days_of_week: [1,2,3,4,5,6,7] },
  { line_number: 'OG-BB-01', departure_time: '09:00', arrival_time: '14:00', base_price: 4500, days_of_week: [1,2,3,4,5,6,7] },
  { line_number: 'OG-BB-01', departure_time: '15:00', arrival_time: '20:00', base_price: 4500, days_of_week: [1,2,3,4,5,6,7] },
  
  // TSR (Prix bas)
  { line_number: 'TSR-BB-01', departure_time: '07:00', arrival_time: '11:40', base_price: 4500, days_of_week: [1,2,3,4,5,6,7] },
  { line_number: 'TSR-BB-01', departure_time: '14:00', arrival_time: '18:40', base_price: 4500, days_of_week: [1,2,3,4,5,6,7] },
  
  // STAF
  { line_number: 'STAF-OB', departure_time: '06:30', arrival_time: '11:20', base_price: 5000, days_of_week: [1,2,3,4,5,6,7] },
  { line_number: 'STAF-OB', departure_time: '13:00', arrival_time: '17:50', base_price: 5000, days_of_week: [1,2,3,4,5,6,7] },
  
  // RAHIMO (Premium)
  { line_number: 'RH-PREMIUM-BB', departure_time: '08:00', arrival_time: '12:30', base_price: 6500, days_of_week: [1,2,3,4,5,6,7] },
  { line_number: 'RH-PREMIUM-BB', departure_time: '16:00', arrival_time: '20:30', base_price: 6500, days_of_week: [1,2,3,4,5,6,7] },
  
  // RAKIETA (Prix officiel 2023: 7500 FCFA)
  { line_number: 'RAK-OB', departure_time: '07:30', arrival_time: '12:40', base_price: 7500, days_of_week: [1,2,3,4,5,6,7] },
  { line_number: 'RAK-OB', departure_time: '13:30', arrival_time: '18:40', base_price: 7500, days_of_week: [1,2,3,4,5,6,7] },
  
  // TCV
  { line_number: 'TCV-BB', departure_time: '10:00', arrival_time: '14:55', base_price: 5000, days_of_week: [1,2,3,4,5,6,7] },

  // Bobo → Ouaga (Retours)
  { line_number: 'BB-OG-01', departure_time: '06:00', arrival_time: '11:00', base_price: 4500, days_of_week: [1,2,3,4,5,6,7] },
  { line_number: 'BB-OG-01', departure_time: '14:00', arrival_time: '19:00', base_price: 4500, days_of_week: [1,2,3,4,5,6,7] },
  { line_number: 'TSR-BB-02', departure_time: '07:00', arrival_time: '11:40', base_price: 4500, days_of_week: [1,2,3,4,5,6,7] },
  { line_number: 'STAF-BO', departure_time: '08:00', arrival_time: '12:50', base_price: 5000, days_of_week: [1,2,3,4,5,6,7] },
  { line_number: 'RH-PREMIUM-BO', departure_time: '09:00', arrival_time: '13:30', base_price: 6500, days_of_week: [1,2,3,4,5,6,7] },

  // Ouaga → Fada
  { line_number: 'OG-FD-01', departure_time: '07:00', arrival_time: '10:30', base_price: 3500, days_of_week: [1,2,3,4,5,6,7] },
  { line_number: 'OG-FD-01', departure_time: '14:00', arrival_time: '17:30', base_price: 3500, days_of_week: [1,2,3,4,5,6,7] },
  { line_number: 'TSR-FD', departure_time: '08:00', arrival_time: '11:15', base_price: 3500, days_of_week: [1,2,3,4,5,6,7] },
  { line_number: 'RAK-FD', departure_time: '09:00', arrival_time: '12:40', base_price: 3500, days_of_week: [1,2,3,4,5,6,7] },
  { line_number: 'TCV-FD', departure_time: '10:00', arrival_time: '13:20', base_price: 4000, days_of_week: [1,2,3,4,5,6,7] },

  // Ouaga → Koudougou
  { line_number: 'OG-KD-01', departure_time: '06:30', arrival_time: '08:00', base_price: 2000, days_of_week: [1,2,3,4,5,6,7] },
  { line_number: 'OG-KD-01', departure_time: '10:00', arrival_time: '11:30', base_price: 2000, days_of_week: [1,2,3,4,5,6,7] },
  { line_number: 'OG-KD-01', departure_time: '15:00', arrival_time: '16:30', base_price: 2000, days_of_week: [1,2,3,4,5,6,7] },
  { line_number: 'STAF-KD', departure_time: '07:00', arrival_time: '08:25', base_price: 2500, days_of_week: [1,2,3,4,5,6,7] },

  // Ouaga → Kaya
  { line_number: 'RH-KAYA', departure_time: '08:00', arrival_time: '09:35', base_price: 2500, days_of_week: [1,2,3,4,5,6,7] },
  { line_number: 'RAK-KAYA', departure_time: '09:00', arrival_time: '10:40', base_price: 2000, days_of_week: [1,2,3,4,5,6,7] },

  // RAKIETA Sud-Ouest (Prix officiels 2023)
  { line_number: 'RAK-BF', departure_time: '07:00', arrival_time: '13:30', base_price: 9000, days_of_week: [1,2,3,4,5,6,7] },
  { line_number: 'RAK-BF-R', departure_time: '08:00', arrival_time: '14:30', base_price: 9000, days_of_week: [1,2,3,4,5,6,7] },
  { line_number: 'RAK-NG', departure_time: '06:30', arrival_time: '13:30', base_price: 9500, days_of_week: [1,2,3,4,5,6] },
  { line_number: 'RAK-NG-R', departure_time: '07:00', arrival_time: '14:00', base_price: 9500, days_of_week: [1,2,3,4,5,6] },

  // RAKIETA International (Prix officiels 2023)
  { line_number: 'RAK-ABIDJAN', departure_time: '17:00', arrival_time: '14:00', base_price: 32500, days_of_week: [2,4,6] }, // Départ soir, arrivée lendemain
  { line_number: 'RAK-ABIDJAN-R', departure_time: '18:00', arrival_time: '15:00', base_price: 32500, days_of_week: [1,3,5] },
  { line_number: 'RAK-BAMAKO', departure_time: '16:00', arrival_time: '14:00', base_price: 20500, days_of_week: [1,3,5,7] },
  { line_number: 'RAK-BAMAKO-R', departure_time: '17:00', arrival_time: '15:00', base_price: 20500, days_of_week: [2,4,6] },
  { line_number: 'RAK-SIKASSO', departure_time: '06:00', arrival_time: '14:00', base_price: 13500, days_of_week: [1,2,3,4,5,6] },
  { line_number: 'RAK-SIKASSO-R', departure_time: '07:00', arrival_time: '15:00', base_price: 13500, days_of_week: [1,2,3,4,5,6] },
  { line_number: 'RAK-BOUAKE', departure_time: '08:00', arrival_time: '23:00', base_price: 26500, days_of_week: [2,4,6] },
  { line_number: 'RAK-BOUAKE-R', departure_time: '09:00', arrival_time: '00:00', base_price: 26500, days_of_week: [1,3,5] },
  { line_number: 'RAK-YAKO', departure_time: '08:00', arrival_time: '09:45', base_price: 1800, days_of_week: [1,2,3,4,5,6,7] },
  { line_number: 'RAK-YAKO', departure_time: '14:00', arrival_time: '15:45', base_price: 1800, days_of_week: [1,2,3,4,5,6,7] },
  { line_number: 'RAK-YAKO-R', departure_time: '09:00', arrival_time: '10:45', base_price: 1800, days_of_week: [1,2,3,4,5,6,7] },
  { line_number: 'RAK-YAKO-R', departure_time: '15:00', arrival_time: '16:45', base_price: 1800, days_of_week: [1,2,3,4,5,6,7] },

  // TCV Lomé (Prix estimés témoignages: ~20000 FCFA)
  { line_number: 'TCV-LOME', departure_time: '06:00', arrival_time: '00:00', base_price: 20000, days_of_week: [7] }, // Dimanche uniquement selon témoignages
  { line_number: 'TCV-LOME-R', departure_time: '07:00', arrival_time: '01:00', base_price: 20000, days_of_week: [1] }, // Retour lundi

  // Lignes urbaines SOTRACO (prix fixes 200 FCFA)
  { line_number: 'L1', departure_time: '06:00', arrival_time: '06:35', base_price: 200, days_of_week: [1,2,3,4,5,6] },
  { line_number: 'L2', departure_time: '06:00', arrival_time: '06:38', base_price: 200, days_of_week: [1,2,3,4,5,6] },
  { line_number: 'L2B', departure_time: '06:00', arrival_time: '06:55', base_price: 200, days_of_week: [1,2,3,4,5,6] },
  { line_number: 'L3', departure_time: '06:00', arrival_time: '06:48', base_price: 200, days_of_week: [1,2,3,4,5,6] },
  { line_number: 'L4', departure_time: '06:00', arrival_time: '06:42', base_price: 200, days_of_week: [1,2,3,4,5,6] },
  { line_number: 'L5', departure_time: '06:00', arrival_time: '06:45', base_price: 200, days_of_week: [1,2,3,4,5,6] },
  { line_number: 'L6', departure_time: '06:00', arrival_time: '06:40', base_price: 200, days_of_week: [1,2,3,4,5,6] },
  { line_number: 'L6B', departure_time: '06:00', arrival_time: '06:50', base_price: 200, days_of_week: [1,2,3,4,5,6] },
  { line_number: 'L10', departure_time: '06:00', arrival_time: '06:36', base_price: 200, days_of_week: [1,2,3,4,5,6,7] },
  { line_number: 'L11', departure_time: '06:00', arrival_time: '06:43', base_price: 200, days_of_week: [1,2,3,4,5,6] },
  { line_number: 'L12', departure_time: '06:00', arrival_time: '06:40', base_price: 200, days_of_week: [1,2,3,4,5,6] },
  { line_number: 'L13', departure_time: '06:00', arrival_time: '06:46', base_price: 200, days_of_week: [1,2,3,4,5,6] },
  { line_number: 'L14', departure_time: '06:00', arrival_time: '06:44', base_price: 200, days_of_week: [1,2,3,4,5,6] },
  { line_number: 'L15', departure_time: '06:00', arrival_time: '06:52', base_price: 200, days_of_week: [1,2,3,4,5,6] },
  { line_number: 'L16', departure_time: '06:00', arrival_time: '06:50', base_price: 200, days_of_week: [1,2,3,4,5,6] },
  { line_number: 'L17', departure_time: '06:00', arrival_time: '06:34', base_price: 200, days_of_week: [1,2,3,4,5,6,7] },
  { line_number: 'L18', departure_time: '06:00', arrival_time: '06:48', base_price: 200, days_of_week: [1,2,3,4,5,6] },
];

module.exports = {
  companies,
  urbanLines,
  interurbanLines,
  schedules,
};
