// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANOSSQBUdsSP1QA9RnEBjNKafaz8JhRTY',
    appId: '1:489782155468:android:7d00bacf7fdac7f37e8a69',
    messagingSenderId: '489782155468',
    projectId: 'ankata-transport',
    storageBucket: 'ankata-transport.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANOSSQBUdsSP1QA9RnEBjNKafaz8JhRTY',
    appId: '1:489782155468:ios:placeholder_ios',
    messagingSenderId: '489782155468',
    projectId: 'ankata-transport',
    storageBucket: 'ankata-transport.firebasestorage.app',
    iosBundleId: 'com.ankata.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANOSSQBUdsSP1QA9RnEBjNKafaz8JhRTY',
    appId: '1:489782155468:macos:placeholder_macos',
    messagingSenderId: '489782155468',
    projectId: 'ankata-transport',
    storageBucket: 'ankata-transport.firebasestorage.app',
    iosBundleId: 'com.ankata.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANOSSQBUdsSP1QA9RnEBjNKafaz8JhRTY',
    appId: '1:489782155468:web:placeholder_web',
    messagingSenderId: '489782155468',
    projectId: 'ankata-transport',
    storageBucket: 'ankata-transport.firebasestorage.app',
    authDomain: 'ankata-transport.firebaseapp.com',
  );
}
